backend:
  name: git-gateway
  repo: hazubeep/strata-academy-local
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/29205f66-9d1b-4db4-8126-7292fa2c0bdd/pkce
  auth_token_endpoint: /sites/29205f66-9d1b-4db4-8126-7292fa2c0bdd/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://strata-academy-local.vercel.app
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Landing Page Content"
    files:
      - name: "landing"
        label: "Landing Page"
        file: "content/landing-page.json" # File target
        description: "Edit konten teks di Landing Page"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Description", name: "hero_desc", widget: "text" }
          - { label: "Call to Action Text", name: "cta_text", widget: "string" }
          - label: "Features Section"
            name: "features"
            widget: "list"
            fields:
              - { label: "Feature Name", name: "name", widget: "string" }
              - { label: "Feature Detail", name: "detail", widget: "text" }          
